[package]
name = "falange-rmk"
version = "0.2.0"
description = "Keyboard firmware written in Rust"
readme = "README.md"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
display-interface = "0.5.0"
ssd1306 = { version = "0.10.0", features = ["async"] }
embedded-graphics = "0.8.1"
log = { version = "0.4" }
# rmk = { default-features = false, git = "https://github.com/HaoboGu/rmk.git", rev = "b91715bd9dd01c4134b1fece7eb3a82e1437d0a8", features = [
rmk = { default-features = false, path = "../rmk/rmk", features = [
    "nrf52840_ble",
    "split",
    "async_matrix",
    "adafruit_bl",
    "controller",
    "usb_log",
    "col2row",
    "storage",
    "vial",
    "vial_lock"
] }
nrf-sdc = { version = "0.3", default-features = false, features = [
    "defmt",
    "peripheral",
    "central",
    "nrf52840",
] }
nrf-mpsl = { version = "0.3", default-features = false, features = [
    "defmt",
    "critical-section-impl",
    "nrf52840",
] }
bt-hci = { version = "0.4", default-features = false, features = ["defmt"] }

cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embassy-time = { version = "0.5", features = ["tick-hz-32_768", "defmt", "defmt-timestamp-uptime"] }
embassy-nrf = { version = "0.7", features = [
    "defmt",
    "nrf52840",
    "time-driver-rtc1",
    "gpiote",
    "unstable-pac",
    "nfc-pins-as-gpio",
    "time",
] }
embassy-executor = { version = "0.9", features = [
    "defmt",
    "arch-cortex-m",
    "executor-thread",
] }
defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
static_cell = "2"

rand = { version = "0.8.4", default-features = false }
rand_core = { version = "0.6" }
rand_chacha = { version = "0.3", default-features = false }


[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"

# Split keyboard example
[[bin]]
name = "central"
path = "src/central.rs"

[[bin]]
name = "peripheral"
path = "src/peripheral.rs"

[profile.dev]
codegen-units = 1      # better optimizations
debug = true
opt-level = 1
overflow-checks = true
lto = false
panic = 'unwind'

[profile.release]
codegen-units = 1       # better optimizations
debug = true            # no overhead for bare-metal
opt-level = "z"         # optimize for binary size
overflow-checks = false
lto = "fat"
